<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@stack('page', 'Home') | {{ \App\Helpers\GeneralHelper::getSetting('site_name') }}</title>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ \App\Helpers\GeneralHelper::getSetting('site_desc') }}">
    <meta property="og:locale" content="en_EN" />
    <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
    <meta property="og:site_name" content="{{ \App\Helpers\GeneralHelper::getSetting('site_name') }}" />
    <meta property="og:type" content="website" />
    <meta name="author" content="Cuialy Software">
    <meta name="publisher" content="Cuialy Software">
    <meta name="google-site-verification" content="{{ \App\Helpers\GeneralHelper::getSetting('google_code') }}" />
    <meta name="copyright" content="Copyright © {{ date('Y') }}, Cuaily Software" />
    <meta property="canonical" href="{{ url()->current() }}" type="text/html" />
    <meta property="og:title" content="@stack('page', 'Home') | {{ \App\Helpers\GeneralHelper::getSetting('site_name') }}" />
    <meta property="og:description" content="{{ \App\Helpers\GeneralHelper::getSetting('site_desc') }}" />
    <meta property="og:url" content="{{ url()->current() }}" />
    <base href="/">
    <link rel="icon" href="{{ asset('dist/img/logo.png') }}" type="image/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dist/css/main.css') }}">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="{{ asset('main.js') }}"></script>
    {!! \App\Helpers\GeneralHelper::getSetting('header_code') !!}
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">
  @include('layouts.header')
    <div class="content-wrapper">
       @hasSection('containerHeader')
           @yield('containerHeader')
        @else
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6"></div>
                        <div class="col-sm-6"><ol class="breadcrumb float-sm-right"></ol></div>
                    </div>
                </div>
            </div>
       @endif
        <div class="content" style="background-color: #27374D;">
            <div class="container">
                @yield('content')
            </div>
        </div>
    </div>
    <footer class="main-footer">
        <div class="float-right d-none d-sm-inline">
            Generated By <a target="_blank" href="https://github.com/Cuialy">Cuialy Software</a>
        </div>
        <strong>Copyright &copy; {{ date('Y') }} | </strong> <a target="_blank" href="https://github.com/Cuialy/qr-url-access">This Project Is Open Source</a>
    </footer>
</div>
@if (session()->has('alert'))
    <script>
        swal(
            "{{ session('alert.title') }}",
            "{{ session('alert.text') }}",
            "{{ session('alert.type') }}"
        );
    </script>
@endif
@if ($errors->any())
    <script>
        swal("Error!", "{{ $errors->first() }}", "error");
    </script>
@endif
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
<script src="{{ route('cuaily-js') }}"></script>
@stack('js')
</body>
</html>
